### ISSUE TITLE
gshell 2.6.5 build fails with jline 2.10

### ISSUE THREAD

**Issue by puntogil** [jdillon/gshell#2]
hi,
gshell 2.6.5 build fails with jline 2.10

[ERROR] /builddir/build/BUILD/gshell-2.6.5/gshell-util/src/main/java/org/sonatype/gshell/util/io/PromptReader.java:[46,15] error: no suitable constructor found for ConsoleReader(InputStream,PrintWriter,Terminal)
[ERROR]     constructor ConsoleReader.ConsoleReader(String,InputStream,OutputStream,Terminal,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor ConsoleReader.ConsoleReader(String,InputStream,OutputStream,Terminal) is not applicable
      (actual and formal argument lists differ in length)
    constructor ConsoleReader.ConsoleReader(InputStream,OutputStream,Terminal) is not applicable
      (actual argument PrintWriter cannot be converted to OutputStream by method invocation conversion)
    constructor ConsoleReader.ConsoleReader(InputStream,OutputStream) is not applicable
      (actual and formal argument lists differ in length)
    constructor ConsoleReader.ConsoleReader() is not applicable
      (actual and formal argument lists differ in length)
/builddir/build/BUILD/gshell-2.6.5/gshell-util/src/main/java/org/sonatype/gshell/util/io/InputPipe.java:[80,19] error: cannot find symbol
thanks
regards
p.s. the jline2 groupId was changed from org.sonatype.jline to  jline

**Comment by jdillon** [comment]
finally (years later) got around to updating gshell to latest jline3 as well as other modernization updates.
